channel/urls.py
from django.urls import path

from . import views

app_name = 'channel'

urlpatterns = [
    path('<slug>/', views.ChannelDetailView.as_view(), name='channel_detail'),
    path('edit_channel', views.channel_update, name='channel_update'),
    path('', views.ChannelListView.as_view(), name='channel_list'),
]

satanhto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('watchplace/', include('watchplace.urls', namespace='watchplace')),
    path('sauce/', include('sauce.urls', namespace='sauce')),
    path('channel/', include('channel.urls', namespace='channel')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sauce/urls.py
from django.urls import path
from . import views

app_name = 'sauce'

urlpatterns = [
    path('', views.SeriesListView.as_view(), name='series_list'),
    path('series/create/', views.SeriesCreateView.as_view(), name='series_create'),
    path('series/<slug>/update/', views.SeriesListUpdate.as_view(), name='series_update'),
    path('series/<slug>/delete/', views.SeriesListDelete.as_view(), name='series_delete'),

    path('series/<slug>/seasons/', views.SeriesDetailSeasonListView.as_view(), name='season_list'),
    path('series/<int:series_id>/season/create/', views.SeasonCreateUpdateView.as_view(), name='season_create'),
    path('series/<int:series_id>/season/<int:season_id>/edit', views.SeasonCreateUpdateView.as_view(), name='season_edit'),
    path('series/<int:series_id>/season/<int:season_id>/delete', views.season_delete, name='season_delete'),

    path('season/<int:pk>/<slug>/episodes/', views.SeasonDetailEpisodeListView.as_view(), name='episode_list'), #id no work, pk
    path('season/<int:season_id>/episode/create/', views.EpisodeCreateUpdateView.as_view(), name='episode_create'),
    path('season/<int:season_id>/episode/<int:episode_id>/edit/', views.EpisodeCreateUpdateView.as_view(), name='episode_edit'),
    path('season/<int:season_id>/episode/<int:episode_id>/delete', views.episode_delete, name='episode_delete'),

    path('<int:pk>/', views.EpisodeDetailView.as_view(), name='episode_detail'),

]

watchplace/urls.py
from django.urls import path

from . import views

app_name = 'watchplace'

urlpatterns = [
    
    path('<slug>/', views.SeriesDetail.as_view(), name='series_detail'),
    path('<int:pk>/<slug>/', views.EpisodeDetail.as_view(), name='episode_detail'),
    path('', views.SeriesList.as_view(), name='series_list'),
]

watchplace/models.py
from django.db import models
from django.conf import settings

from sauce.models import Series

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='comments', on_delete=models.CASCADE)
    series = models.ForeignKey(Series, related_name='comments', on_delete=models.CASCADE)

    body = models.TextField()

    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.user.username}\'s comment on {self.series}'

watchplace/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body',]

watchplace/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin

from sauce.models import Series, Season, Episode

from .forms import CommentForm

class SeriesList(LoginRequiredMixin, ListView):
    queryset = Series.objects.all()
    context_object_name = 'series_list'
    template_name = 'watchplace/watch/series_list.html'

class SeriesDetail(LoginRequiredMixin, DetailView):
    model = Series
    context_object_name = 'series'
    template_name = 'watchplace/watch/series_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['seasons'] = Season.objects.filter(series=context['series'])
        context['comment_form'] = CommentForm
        return context

    def post(self, request, slug, *args, **kwargs):
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.instance.user = self.request.user
            form.instance.series = Series.objects.get(slug=slug)
            form.save()
            return redirect('watchplace:series_detail', slug=slug)

class EpisodeDetail(LoginRequiredMixin, DetailView):
    model = Episode
    context_object_name = 'episode'
    template_name = 'watchplace/watch/episodes.html'

watchplace/templates/watchplace/watch/episodes.html
{% extends "base.html" %}

{% block title %}
{{ episode.title }}
{% endblock %}

{% block content %}
{{ episode.season.series.name }}</br>
{{ episode.season.name }}</br>
{{ episode.order }}. {{ episode.title }}</br>

<video controls>
    <source src="{{ episode.file.url }}" type="video/mp4">
</video>
{% endblock %}

watchplace/templates/watchplace/watch/series_detail.html
{% extends "base.html" %}

{% block title %}
{{ series.name }}
{% endblock %}

{% block content %}

<h1>{{ series.name }}</h1>

<!-- If series has cover -->
{% if series.cover %}
<img src="{{ series.cover.url }}" /></br>
{% endif %}


Hepburn - {{ series.hepburn }}</br>
Description - {{ series.description }}</br>
Owner - <a href="{% url "view_profile" series.owner.username %}">{{ series.owner.username }}</a>
{% if series.owner.profile.channel %}
of <a href="{% url "channel:channel_detail" series.owner.profile.channel.slug %}">{{ series.owner.profile.channel.name }}</a>
{% endif %}</br>

<!-- Optmize above code in view -->

Created on - {{ series.created }}</br>
Updated on - {{ series.updated }}</br>

<h2>Season List</h2>
{% for season in seasons %}
{{ season.name }}</br>
{% for episode in season.episodes.all %}
{{ episode.order }}. {{ episode.title }} - <a href="{% url "watchplace:episode_detail" episode.id episode.slug %}">Watch</a></br>
{% empty %}
No episodes yet.
{% endfor %}
</br>
{% empty %}
No seasons yet.
{% endfor %}

<!-- Comments -->
Leave a comment
<form method="POST">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Done">
</form>

<h1>Comments</h1>
{% for comment in series.comments.all %}
<div class="comment{% if comment.user.profile in series.owner.profile.channel.members.all %} admin{% endif %}">
    <a href="{% url "view_profile" comment.user.username %}">
        <img class="comment" src="{{ comment.user.profile.picture.url }}">
        {{ comment.user.username }}
    </a>
    {{ comment.created }}</br>
    {{ comment.body }}
</div>
{% empty %}
No one commented, be out first.
{% endfor %}

{% endblock %}

watchplace/templates/watchplace/watch/series_list.html
{% extends "base.html" %}

{% block title %}
Series List
{% endblock %}

{% block content %}

{% for series in series_list %}
<a href="{% url "watchplace:series_detail" series.slug %}">
{{ series.name }}</br>
</a>
{% empty %}No series yet.
{% endfor %}

{% endblock %}