channel/urls.py
from django.urls import path

from . import views

app_name = 'channel'

urlpatterns = [
    path('<slug>/', views.ChannelDetailView.as_view(), name='channel_detail'),
    path('edit_channel', views.channel_update, name='channel_update'),
    path('', views.ChannelListView.as_view(), name='channel_list'),
]

satanhto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('watchplace/', include('watchplace.urls', namespace='watchplace')),
    path('sauce/', include('sauce.urls', namespace='sauce')),
    path('channel/', include('channel.urls', namespace='channel')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sauce/urls.py
from django.urls import path
from . import views

app_name = 'sauce'

urlpatterns = [
    path('', views.SeriesListView.as_view(), name='series_list'),
    path('series/create/', views.SeriesCreateView.as_view(), name='series_create'),
    path('series/<slug>/update/', views.SeriesListUpdate.as_view(), name='series_update'),
    path('series/<slug>/delete/', views.SeriesListDelete.as_view(), name='series_delete'),

    path('series/<slug>/seasons/', views.SeriesDetailSeasonListView.as_view(), name='season_list'),
    path('series/<int:series_id>/season/create/', views.SeasonCreateUpdateView.as_view(), name='season_create'),
    path('series/<int:series_id>/season/<int:season_id>/edit', views.SeasonCreateUpdateView.as_view(), name='season_edit'),
    path('series/<int:series_id>/season/<int:season_id>/delete', views.season_delete, name='season_delete'),

    path('season/<int:pk>/<slug>/episodes/', views.SeasonDetailEpisodeListView.as_view(), name='episode_list'), #id no work, pk
    path('season/<int:season_id>/episode/create/', views.EpisodeCreateUpdateView.as_view(), name='episode_create'),
    path('season/<int:season_id>/episode/<int:episode_id>/edit/', views.EpisodeCreateUpdateView.as_view(), name='episode_edit'),
    path('season/<int:season_id>/episode/<int:episode_id>/delete', views.episode_delete, name='episode_delete'),

    path('<int:pk>/', views.EpisodeDetailView.as_view(), name='episode_detail'),

]

watchplace/urls.py
from django.urls import path

from . import views

app_name = 'watchplace'

urlpatterns = [
    
    path('<slug>/', views.SeriesDetail.as_view(), name='series_detail'),
    path('<int:pk>/<slug>/', views.EpisodeDetail.as_view(), name='episode_detail'),
    path('', views.SeriesList.as_view(), name='series_list'),
]

channel/models.py
from django.db import models

from sauce.ImageUploadLocation import channel_dir

class Channel(models.Model):
    name = models.CharField(max_length=250, help_text='Just in case, be unique!')
    slug = models.SlugField(unique=True)
    logo = models.ImageField(upload_to=channel_dir, blank=True, null=True)
    description = models.TextField(help_text='You might want to let ppl know some infos \'bout your channel. Markdown is supported here.')

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

channel/forms.py
from django import forms

from .models import Channel

class ChannelUpdateForm(forms.ModelForm):
    class Meta:
        model = Channel
        exclude = ['slug', 'created', 'updated']

channel/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.utils.text import slugify #To slugify channel name in channel form
from django.contrib.auth.decorators import permission_required

from .forms import ChannelUpdateForm

from .models import Channel
from sauce.models import Series

class ChannelListView(ListView):
    model = Channel
    context_object_name = 'channels'
    template_name = 'channel/channel_list.html'

class ChannelDetailView(DetailView):
    model = Channel
    context_object_name = 'channel'
    # series_uploaded = Series.objects.filter(owner__in=)
    template_name = 'channel/channel_detail.html'

    # Filter series uploaded by channel members 
    # and send the filtered list to template as
    # 'series_uploaded' variable
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        channel_obj = context['channel'] # Get the channel object
        channel_members = channel_obj.members.all() # Get the channel's member as queryset
        series_uploaded = Series.objects.filter(owner__profile__in=channel_members) # Filter series
        context['series_uploaded'] = series_uploaded
        return context

# Channel Update View
@permission_required('channel.change_channel', raise_exception=True)
def channel_update(request):
    user_channel = request.user.profile.channel
    if request.method == 'POST':
        form = ChannelUpdateForm(data=request.POST, instance=user_channel, files=request.FILES)
        if form.is_valid():
            form.save(commit=False)
            form.instance.slug = slugify(form.instance.name)
            form.save()
            return redirect('profile')
    else:
        form = ChannelUpdateForm(instance=user_channel)
    return render(request, 'channel/channel_update.html', {'form': form})

channel/templates/channel/channel_detail.html
{% extends "base.html" %}
{% load channel_tags %}

{% block title %}
{{ channel.name }}
{% endblock %}

{% block content %}

<!-- If channel has logo -->
{% if channel.logo %}
<img src="{{ channel.logo.url }}" /></br>
{% endif %}

<h1>{{ channel.name }}</h1>

<p>{{ channel.description|markdown }}</p></br>
Collobrated since {{ channel.created }}</br>
Latest updated on {{ channel.updated }}</br>

<!-- Member list -->
Members:
<ul>
    {% for member in channel.members.all %}
    <li>
        <a href="{% url "view_profile" member.owner.username %}">{{ member.owner.username }}</a>
    </li>
    {% empty %}
    No-member channel! Weird, right?
    {% endfor %}
</ul>

<!-- Series Uploaded from members -->
<h1>Uploaded Series</h1>
{% for series in series_uploaded %}
<a href="{% url "watchplace:series_detail" series.slug %}">
{{ series.name }}
</a></br>
{% endfor %}

{% endblock %}

channel/templates/channel/channel_list.html
{% extends "base.html" %}

{% block title %}
Channel List
{% endblock %}

{% block content %}

{% for channel in channels %}
<a href="{% url "channel:channel_detail" channel.slug %}">
{{ channel.name }}</br>
</a>
{% empty %}No channels yet.
{% endfor %}

{% endblock %}

channel/templates/channel/channel_update.html
{% extends "base.html" %}

{% block title %}
Edit your channel
{% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Save">
</form>

{% endblock %}